name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake
        python -m pip install --upgrade pip
        pip install -f https://download.pytorch.org/whl/cpu/torch_stable.html torch==2.0.0 --only-binary=:all:

    - name: Debug Google Test submodule
      run: |
        cd googletest
        echo "Google Test submodule path: $(pwd)"
        git log -1 --pretty=format:"%h - %s (%ci)" --abbrev-commit
        cd ..

    - name: Run test.sh script
      run: |
        chmod +x test.sh
        ./test.sh
